#!/usr/bin/env bash
set -xeuo pipefail

cd "$(git rev-parse --show-toplevel)"
npx browserify jsdom.src.js -o jsdom.bundled.js
npx esbuild --bundle index.jsx --outfile=index.bundled.js
npx esbuild --bundle worker.jsx --outfile=worker.bundled.js